"""Build privacy-safe Kyrgyz conversational style assets from Telegram export.

The raw export is read only by this offline tool. Production imports only the
small derived files in ``data`` and never opens or uploads ``result1.json``.
"""

from __future__ import annotations

import argparse
import hashlib
import heapq
import json
import re
import statistics
from collections import Counter
from pathlib import Path


URL_RE = re.compile(r"(?i)\b(?:https?://|www\.|t\.me/|telegram\.me/)\S+")
EMAIL_RE = re.compile(r"(?i)\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b")
USERNAME_RE = re.compile(r"(?<!\w)@[A-Za-z0-9_]{4,}")
PHONE_RE = re.compile(r"(?<!\w)\+?\d[\d ()-]{7,}\d(?!\w)")
LONG_ID_RE = re.compile(r"\d{7,}")
TOKEN_RE = re.compile(r"[0-9A-Za-zА-Яа-яЁёҢңӨөҮүҚқҒғҺһ]+", re.UNICODE)
CYRILLIC_RE = re.compile(r"[А-Яа-яЁёҢңӨөҮүҚқҒғҺһ]", re.UNICODE)
EMOJI_RE = re.compile("[\U0001F300-\U0001FAFF\u2600-\u27BF]")

KY_WORDS = {
    "азыр", "анан", "анда", "бар", "барбы", "барып", "бара", "бер", "берчи", "берчи", "берем",
    "болду", "болот", "болбойт", "болсо", "боло", "бул", "бүгүн", "дагы", "деген", "дейм", "деп",
    "дос", "досум", "эле", "эмне", "эми", "жакшы", "жок", "жибер", "жиберчи", "кайда", "кандай",
    "канча", "качан", "келе", "келет", "керек", "кылып", "кылам", "кыласың", "күт", "мага", "мен",
    "менен", "не", "ошол", "ошондо", "ооба", "сага", "сен", "силер", "сураныч", "ушул", "үчүн",
    "чейин", "чыгат", "чыгарып", "экен", "экенин", "эртең", "тез", "акча", "сом", "котор", "которуп",
    "түштү", "түшө", "түшүнбөдүм", "таап", "ал", "алып", "кой", "койчу", "каттоо", "утту", "утса",
    "уткан", "утулат", "оюнчу", "оюнчулар", "каттал", "кир", "ач", "ачып", "иште", "иштейт",
}
RU_WORDS = {
    "а", "без", "брат", "будет", "вам", "вас", "вот", "все", "где", "да", "давай", "деньги",
    "для", "его", "если", "есть", "ещё", "зачем", "как", "когда", "кто", "можно", "можешь", "мне",
    "надо", "нет", "нужно", "он", "она", "они", "потом", "почему", "привет", "просто", "работа",
    "сейчас", "скинь", "сколько", "спасибо", "сюда", "там", "тебе", "ты", "уже", "что", "это", "я",
    "аккаунт", "баланс", "карта", "перевод", "процент", "комиссия", "скрин", "ссылка", "сумма",
}
AD_PATTERNS = (
    "вакансия", "требуется сотрудник", "ищем сотрудников", "заработок без вложений", "удаленная работа",
    "розыгрыш", "giveaway", "подпишись", "подпишитесь", "реклама", "оплата ежедневно", "доход в день",
    "набор в команду", "ищем менеджера", "ищем агента", "работа для всех", "пассивный доход",
)
AUTOGENERATED_PATTERNS = (
    "this message was deleted", "message deleted", "автоматическое уведомление", "добро пожаловать в группу",
)

CURATED_SLANG_HINTS = [
    {"form": "азыр", "meaning_ru": "сейчас", "note": "обычная короткая форма"},
    {"form": "болду", "meaning_ru": "ладно / готово / хватит", "note": "значение зависит от контекста"},
    {"form": "барбы", "meaning_ru": "есть? / имеется?", "note": "короткий вопрос"},
    {"form": "жок", "meaning_ru": "нет", "note": "разговорная базовая форма"},
    {"form": "канча", "meaning_ru": "сколько", "note": "часто про цену или сумму"},
    {"form": "котор", "meaning_ru": "переведи / отправь перевод", "note": "смотреть контекст денег"},
    {"form": "жиберчи", "meaning_ru": "скинь пожалуйста", "note": "разговорная просьба"},
    {"form": "күтүп тур", "meaning_ru": "подожди", "note": "обычная чат-фраза"},
    {"form": "эмне болду", "meaning_ru": "что случилось / что такое", "note": "смотреть контекст"},
    {"form": "норм", "meaning_ru": "нормально", "note": "русское слово в mixed RU/KY"},
    {"form": "скинь скрин", "meaning_ru": "пришли скриншот", "note": "естественное переключение кода"},
    {"form": "аккаунт ач", "meaning_ru": "открой аккаунт", "note": "mixed RU/KY"},
    {"form": "баланс толукта", "meaning_ru": "пополни баланс", "note": "mixed RU/KY"},
    {"form": "картага түшөт", "meaning_ru": "поступит на карту", "note": "mixed RU/KY"},
]


def message_text(value: object) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        parts: list[str] = []
        for item in value:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                parts.append(str(item.get("text", "")))
        return "".join(parts)
    return ""


def redact_personal_data(text: str) -> str:
    text = EMAIL_RE.sub("[email]", text)
    text = URL_RE.sub("[link]", text)
    text = USERNAME_RE.sub("[username]", text)
    text = PHONE_RE.sub("[phone]", text)
    text = LONG_ID_RE.sub("[id]", text)
    return re.sub(r"[ \t]+", " ", text).strip()


def normalized_duplicate_key(text: str) -> str:
    return re.sub(r"\W+", " ", text.casefold(), flags=re.UNICODE).strip()


def language_scores(text: str) -> tuple[int, int]:
    tokens = [token.casefold() for token in TOKEN_RE.findall(text)]
    ky = sum(token in KY_WORDS for token in tokens)
    ru = sum(token in RU_WORDS for token in tokens)
    ky += sum(character in "ңөүҢӨҮ" for character in text) * 2
    return ky, ru


def classify_language(text: str) -> str:
    ky, ru = language_scores(text)
    if ky >= 2 and ru >= 2:
        return "mixed_ru_ky"
    if ky >= 2 or (ky >= 1 and ru == 0):
        return "ky"
    if ru >= 2 and ky == 0:
        return "ru"
    cyrillic = len(CYRILLIC_RE.findall(text))
    latin = sum(character.isascii() and character.isalpha() for character in text)
    if latin > cyrillic * 2:
        return "other"
    return "other"


def looks_like_spam(message: dict, text: str) -> bool:
    lowered = text.casefold()
    sender = str(message.get("from", "")).casefold()
    if message.get("type") != "message" or message.get("via_bot"):
        return True
    if sender.endswith("bot") or sender.endswith(" бот"):
        return True
    if message.get("forwarded_from"):
        return True
    if text.lstrip().startswith("/") or len(text) < 2 or len(text) > 280:
        return True
    if any(pattern in lowered for pattern in AD_PATTERNS + AUTOGENERATED_PATTERNS):
        return True
    if text.count("\n") > 4 or len(URL_RE.findall(text)) > 1:
        return True
    letters = [character for character in text if character.isalpha()]
    if len(letters) >= 12 and sum(character.isupper() for character in letters) / len(letters) > 0.75:
        return True
    if re.search(r"(.)\1{7,}", text):
        return True
    return False


def quality_score(text: str, language: str) -> int:
    tokens = TOKEN_RE.findall(text)
    score = 25
    score += 8 if 2 <= len(tokens) <= 16 else 0
    score += 5 if 4 <= len(text) <= 120 else 0
    score += 4 if language == "mixed_ru_ky" else 0
    score += 2 if "?" in text else 0
    score += 2 if EMOJI_RE.search(text) else 0
    score -= text.count("[") * 2
    score -= max(0, len(text) - 160) // 15
    return score


def style_for(text: str) -> str:
    tokens = TOKEN_RE.findall(text)
    slang_hits = sum(token.casefold() in {"брат", "бро", "го", "норм", "пж", "плиз"} for token in tokens)
    if slang_hits or len(tokens) <= 3:
        return "very_casual"
    if len(tokens) <= 12:
        return "casual"
    return "neutral"


def stable_tie_breaker(text: str) -> int:
    return int(hashlib.sha1(text.encode("utf-8")).hexdigest()[:12], 16)


def select_reference_rows(corpus: list[dict], limit: int = 600) -> list[dict]:
    buckets: dict[tuple, list[dict]] = {}
    for item in corpus:
        text = item["text"]
        key = (
            item["language"],
            item["style"],
            bool("?" in text),
            bool(EMOJI_RE.search(text)),
            min(len(TOKEN_RE.findall(text)) // 4, 4),
        )
        buckets.setdefault(key, []).append(item)
    selected: list[dict] = []
    while len(selected) < limit and buckets:
        empty = []
        for key in sorted(buckets, key=str):
            rows = buckets[key]
            if rows:
                item = rows.pop(stable_tie_breaker(str(key)) % len(rows))
                selected.append({
                    "text": item["text"],
                    "language": item["language"],
                    "style": item["style"],
                    "token_count": len(TOKEN_RE.findall(item["text"])),
                    "question": "?" in item["text"],
                    "emoji": bool(EMOJI_RE.search(item["text"])),
                })
                if len(selected) >= limit:
                    break
            else:
                empty.append(key)
        for key in empty:
            buckets.pop(key, None)
    return selected


def build_assets(source: Path, output_dir: Path, max_corpus: int) -> dict:
    with source.open("r", encoding="utf-8") as handle:
        export = json.load(handle)
    messages = export.get("messages", [])
    deduplicated: set[str] = set()
    heap: list[tuple[int, int, str, str, str]] = []
    stats = Counter(total=len(messages))

    for message in messages:
        raw_text = message_text(message.get("text"))
        if looks_like_spam(message, raw_text):
            stats["filtered_noise"] += 1
            continue
        text = redact_personal_data(raw_text)
        if not text or text in {"[link]", "[username]", "[phone]", "[id]"}:
            stats["filtered_empty_or_entity_only"] += 1
            continue
        duplicate_key = normalized_duplicate_key(text)
        if not duplicate_key or duplicate_key in deduplicated:
            stats["filtered_duplicate"] += 1
            continue
        deduplicated.add(duplicate_key)
        language = classify_language(text)
        if language not in {"ky", "mixed_ru_ky"}:
            stats[f"language_{language}"] += 1
            continue
        stats[f"language_{language}"] += 1
        score = quality_score(text, language)
        row = (score, stable_tie_breaker(text), text, language, style_for(text))
        if len(heap) < max_corpus:
            heapq.heappush(heap, row)
        elif row[:2] > heap[0][:2]:
            heapq.heapreplace(heap, row)

    corpus = [
        {"text": text, "language": language, "style": style}
        for _, _, text, language, style in sorted(heap, key=lambda row: row[1])
    ]
    output_dir.mkdir(parents=True, exist_ok=True)
    corpus_path = output_dir / "kg_conversational_corpus.jsonl"
    with corpus_path.open("w", encoding="utf-8", newline="\n") as handle:
        for row in corpus:
            handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")

    token_frequency: Counter[str] = Counter()
    phrase_frequency: Counter[str] = Counter()
    char_lengths: list[int] = []
    token_lengths: list[int] = []
    punctuation = Counter()
    emoji_messages = 0
    language_counts = Counter()
    style_counts = Counter()
    for row in corpus:
        text = row["text"]
        tokens = [token.casefold() for token in TOKEN_RE.findall(text)]
        token_frequency.update(tokens)
        phrase_frequency.update(" ".join(tokens[index:index + 2]) for index in range(len(tokens) - 1))
        char_lengths.append(len(text))
        token_lengths.append(len(tokens))
        punctuation.update(character for character in text if character in ".,?!…")
        emoji_messages += bool(EMOJI_RE.search(text))
        language_counts[row["language"]] += 1
        style_counts[row["style"]] += 1

    profile = {
        "source": "privacy-safe filtered Telegram corpus",
        "message_count": len(corpus),
        "language_distribution": dict(language_counts),
        "style_distribution": dict(style_counts),
        "average_characters": round(statistics.mean(char_lengths), 2) if char_lengths else 0,
        "median_characters": statistics.median(char_lengths) if char_lengths else 0,
        "average_tokens": round(statistics.mean(token_lengths), 2) if token_lengths else 0,
        "median_tokens": statistics.median(token_lengths) if token_lengths else 0,
        "punctuation_per_message": {
            key: round(value / len(corpus), 4) if corpus else 0 for key, value in punctuation.items()
        },
        "emoji_message_ratio": round(emoji_messages / len(corpus), 4) if corpus else 0,
        "mixed_ru_ky_ratio": round(language_counts["mixed_ru_ky"] / len(corpus), 4) if corpus else 0,
        "guidance": [
            "Mirror the source formality instead of maximizing slang",
            "Keep short messages short",
            "Allow natural Russian/Kyrgyz code switching",
            "Corpus messages are style references, not translations",
        ],
    }
    (output_dir / "kg_style_profile.json").write_text(
        json.dumps(profile, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    common_forms = [
        {"form": token, "frequency": count, "kind": "corpus_frequency_candidate"}
        for token, count in token_frequency.most_common(300)
        if len(token) >= 2
    ][:120]
    common_phrases = [
        {"form": phrase, "frequency": count, "kind": "frequent_chat_phrase"}
        for phrase, count in phrase_frequency.most_common(160)
        if count >= 3
    ][:80]
    slang = {
        "usage": "Context hints only. Never apply these entries with direct word replacement.",
        "curated_hints": CURATED_SLANG_HINTS,
        "frequent_casual_forms": common_forms,
        "frequent_phrases": common_phrases,
    }
    (output_dir / "kg_slang_dictionary.json").write_text(
        json.dumps(slang, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    references = select_reference_rows(corpus)
    (output_dir / "kg_style_references.json").write_text(
        json.dumps(references, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    stats["selected_corpus"] = len(corpus)
    stats["selected_references"] = len(references)
    return {"stats": dict(stats), "profile": profile}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("--output-dir", type=Path, default=Path("data"))
    parser.add_argument("--max-corpus", type=int, default=40_000)
    args = parser.parse_args()
    result = build_assets(args.source, args.output_dir, args.max_corpus)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
